default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: docsync_development
  username: maccari78
  host: localhost
  pool: 5

test:
  <<: *default
  database: docsync_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>