default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: maccari78
  password: <%= ENV["POSTGRES_PASSWORD"] || "" %>

development:
  <<: *default
  database: docsync_development

test:
  <<: *default
  database: docsync_test

production:
  <<: *default
  database: docsync_production
  url: <%= ENV["DATABASE_URL"] if ENV["DATABASE_URL"].present? %>